version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: travel-planner-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: travel_planner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    
volumes:
  postgres_data:
